# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='start_date',
        ),
    ]
