# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_remove_student_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
