# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_student_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='disciplines',
            new_name='discipline',
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestao.Teacher'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
